# Generated by Django 4.2.28 on 2026-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpecXProjaeng", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ram", "RAM"),
                            ("ssd", "SSD"),
                            ("mb_intel", "Mainboard Intel"),
                            ("mb_amd", "Mainboard AMD"),
                            ("psu", "Power Supply"),
                            ("case", "Case"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("spec_text", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=200)),
                ("size", models.DecimalField(decimal_places=1, max_digits=4)),
                ("refresh_rate", models.IntegerField(default=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
