# Generated by Django 4.2.28 on 2026-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpecXProjaeng", "0002_component_monitor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Monitor",
        ),
        migrations.AddField(
            model_name="component",
            name="socket_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="tier",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="component",
            name="wattage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cpu",
            name="socket",
            field=models.CharField(default="AM4", max_length=50),
        ),
        migrations.AddField(
            model_name="cpu",
            name="tdp",
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name="gpu",
            name="power_req",
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name="component",
            name="category",
            field=models.CharField(
                choices=[
                    ("ram", "RAM"),
                    ("ssd", "SSD"),
                    ("mb", "Mainboard"),
                    ("psu", "Power Supply"),
                    ("case", "Case"),
                ],
                max_length=20,
            ),
        ),
    ]
