# Generated by Django 4.2.28 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SpecXProjaeng",
            "0003_delete_monitor_component_socket_type_component_tier_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=200)),
                ("size", models.DecimalField(decimal_places=1, max_digits=4)),
                ("refresh_rate", models.IntegerField(default=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="component",
            name="socket_type",
        ),
        migrations.RemoveField(
            model_name="component",
            name="tier",
        ),
        migrations.RemoveField(
            model_name="component",
            name="wattage",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="socket",
        ),
        migrations.RemoveField(
            model_name="cpu",
            name="tdp",
        ),
        migrations.RemoveField(
            model_name="gpu",
            name="power_req",
        ),
        migrations.AlterField(
            model_name="component",
            name="category",
            field=models.CharField(
                choices=[
                    ("ram", "RAM"),
                    ("ssd", "SSD"),
                    ("mb_intel", "Mainboard Intel"),
                    ("mb_amd", "Mainboard AMD"),
                    ("psu", "Power Supply"),
                    ("case", "Case"),
                ],
                max_length=20,
            ),
        ),
    ]
