# Generated by Django 4.2.28 on 2026-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpecXProjaeng", "0004_monitor_remove_component_socket_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Monitor",
        ),
        migrations.AlterField(
            model_name="component",
            name="category",
            field=models.CharField(
                choices=[
                    ("mb_intel", "Mainboard Intel"),
                    ("mb_amd", "Mainboard AMD"),
                    ("ram", "RAM"),
                    ("ssd", "Storage (SSD/HDD)"),
                    ("psu", "Power Supply"),
                    ("case", "Case"),
                    ("monitor", "Monitor"),
                    ("mouse", "Mouse"),
                    ("keyboard", "Keyboard"),
                    ("headset", "Headset"),
                    ("mic", "Microphone"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="component",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="component",
            name="spec_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="benchmark_score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="benchmark_score",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="price",
            field=models.IntegerField(),
        ),
    ]
