# Generated by Django 4.2.28 on 2026-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpecXProjaeng", "0005_delete_monitor_alter_component_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="ram_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="socket",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="watt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpu",
            name="socket",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
