# Generated by Django 4.2.28 on 2026-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SpecXProjaeng",
            "0006_component_ram_type_component_socket_component_watt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="category",
            field=models.CharField(
                choices=[
                    ("mb_intel", "Mainboard Intel"),
                    ("mb_amd", "Mainboard AMD"),
                    ("ram", "RAM"),
                    ("ssd", "Storage"),
                    ("psu", "Power Supply"),
                    ("case", "Case"),
                    ("monitor", "Monitor"),
                    ("mouse", "Mouse"),
                    ("keyboard", "Keyboard"),
                    ("headset", "Headset"),
                    ("mic", "Microphone"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="watt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
