# Generated by Django 4.2.28 on 2026-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpecXProjaeng", "0007_alter_component_category_alter_component_watt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="watt",
            field=models.IntegerField(default=0),
        ),
    ]
